# This is a basic workflow to help you get started with Actions

name: Check Repository Code Quality

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  python:
    uses: ./.github/workflows/validate-python-code-quality.yml

